TelegramBundle\Entity\Chat:
    type: entity
    table: null
    repositoryClass: TelegramBundle\Repository\ChatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        telegramId:
            type: integer
            column: telegram_id
    lifecycleCallbacks: {  }
