TelegramBundle\Entity\Setting:
    type: entity
    table: null
    repositoryClass: TelegramBundle\Repository\SettingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        value:
            type: string
            length: 255
    lifecycleCallbacks: {  }
