<?php

namespace TelegramBundle\Repository;

use TelegramBundle\Entity\Chat;
use TelegramBundle\Entity\Message;
use TelegramBundle\Entity\User;
use unreal4u\TelegramAPI\Telegram\Types\Message as TelegramMessage;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param TelegramMessage $telegramMessage
     * @param Chat $chat
     * @param User $user
     *
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function saveMessage(TelegramMessage $telegramMessage, Chat $chat, User $user)
    {
        $message = new Message();
        $message->setChat($chat);
        $message->setUser($user);
        $message->setMessage($telegramMessage->text);
        $message->setTelegramId($telegramMessage->message_id);
        $message->setDate(new \DateTime('@' . $telegramMessage->date));

        $entityManager = $this->getEntityManager();
        $entityManager->persist($message);
        $entityManager->flush($message);
    }
}
